#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'schkovich-nodejs_dev',
  :git => 'https://github.com/schkovich/nodejs-dev.git',
  :ref => 'master'

# mod 'schkovich-redis',
#  :git => 'https://github.com/schkovich/evenup-redis.git'

mod 'puppetlabs/nodejs'
mod 'puppetlabs/mongodb'
# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'
