#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'schkovich-nodejs_dev',
  :git => 'https://github.com/schkovich/nodejs-dev.git',
  :ref => 'master'

mod 'schkovich-mongodb32xenial',
  :git => 'https://github.com/schkovich/mongodb32xenial.git',
  :ref => 'master'

mod 'puppet/nodejs'
